blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/kpZ3hWyAaq
    about: Ask questions, get help, and chat with other VERA users.
  - name: Reddit Support
    url: https://www.reddit.com/user/LexSort/
    about: Discuss and share feedback with the community on Reddit.
